#! bin/bin/sh
clear
h=`who | head -1 | tr -s ' ' | cut -d ' ' -f4 | cut -d ':' -f1`
if [ $h -lt 12 ]
then
echo Good Morning
elif [ $h -ge 12 -a $h -lt 17 ]
then
echo Good Afternoon
else
echo Good Evening
fi
